import type { BudgetCategory } from '../types/budget';

/**
 * Mock Federal Budget Data for FY 2025
 * Based on realistic federal budget allocations (~$6.5 trillion total)
 * Includes major departments with drill-down capabilities
 */
export const MOCK_BUDGET_DATA: BudgetCategory[] = [
  {
    id: 'hhs',
    name: 'Health and Human Services',
    allocated: 1700000000000, // $1.7T
    spent: 1450000000000,
    categoryType: 'department',
    description: 'Medicare, Medicaid, CDC, NIH, and other health programs',
    changeFromPriorYear: 0.045, // 4.5% increase
    subcategories: [
      {
        id: 'medicare',
        name: 'Medicare',
        allocated: 900000000000,
        spent: 780000000000,
        categoryType: 'program',
        description: 'Health insurance for seniors and disabled',
        changeFromPriorYear: 0.06,
      },
      {
        id: 'medicaid',
        name: 'Medicaid',
        allocated: 650000000000,
        spent: 580000000000,
        categoryType: 'program',
        description: 'Health coverage for low-income individuals',
        changeFromPriorYear: 0.04,
      },
      {
        id: 'nih',
        name: 'National Institutes of Health',
        allocated: 48000000000,
        spent: 42000000000,
        categoryType: 'agency',
        description: 'Medical research and health innovation',
        changeFromPriorYear: 0.03,
      },
      {
        id: 'cdc',
        name: 'Centers for Disease Control',
        allocated: 17000000000,
        spent: 15000000000,
        categoryType: 'agency',
        description: 'Public health protection and disease prevention',
        changeFromPriorYear: 0.02,
      },
      {
        id: 'fda',
        name: 'Food and Drug Administration',
        allocated: 6500000000,
        spent: 5800000000,
        categoryType: 'agency',
        description: 'Food and drug safety regulation',
        changeFromPriorYear: 0.025,
      },
    ],
  },
  {
    id: 'ssa',
    name: 'Social Security Administration',
    allocated: 1400000000000, // $1.4T
    spent: 1380000000000,
    categoryType: 'department',
    description: 'Social Security retirement and disability benefits',
    changeFromPriorYear: 0.032, // 3.2% increase
    subcategories: [
      {
        id: 'oasi',
        name: 'Old-Age and Survivors Insurance',
        allocated: 1100000000000,
        spent: 1085000000000,
        categoryType: 'program',
        description: 'Retirement and survivors benefits',
        changeFromPriorYear: 0.035,
      },
      {
        id: 'ssdi',
        name: 'Social Security Disability Insurance',
        allocated: 150000000000,
        spent: 148000000000,
        categoryType: 'program',
        description: 'Disability benefits',
        changeFromPriorYear: 0.02,
      },
      {
        id: 'ssi',
        name: 'Supplemental Security Income',
        allocated: 65000000000,
        spent: 63000000000,
        categoryType: 'program',
        description: 'Income assistance for disabled and elderly',
        changeFromPriorYear: 0.028,
      },
      {
        id: 'ssa-admin',
        name: 'Administrative Expenses',
        allocated: 15000000000,
        spent: 14000000000,
        categoryType: 'operations',
        description: 'SSA operations and support',
        changeFromPriorYear: 0.015,
      },
    ],
  },
  {
    id: 'treasury',
    name: 'Department of the Treasury',
    allocated: 1000000000000, // $1T
    spent: 920000000000,
    categoryType: 'department',
    description: 'Interest on national debt and IRS operations',
    changeFromPriorYear: 0.087, // 8.7% increase (rising interest rates)
    subcategories: [
      {
        id: 'interest',
        name: 'Interest on National Debt',
        allocated: 880000000000,
        spent: 850000000000,
        categoryType: 'program',
        description: 'Debt service payments',
        changeFromPriorYear: 0.095,
      },
      {
        id: 'irs',
        name: 'Internal Revenue Service',
        allocated: 14500000000,
        spent: 13000000000,
        categoryType: 'agency',
        description: 'Tax collection and enforcement',
        changeFromPriorYear: 0.18, // IRA funding boost
      },
      {
        id: 'mint',
        name: 'U.S. Mint',
        allocated: 850000000,
        spent: 780000000,
        categoryType: 'agency',
        description: 'Coin production',
        changeFromPriorYear: -0.05,
      },
      {
        id: 'treasury-ops',
        name: 'Departmental Operations',
        allocated: 3500000000,
        spent: 3100000000,
        categoryType: 'operations',
        description: 'Treasury management and oversight',
        changeFromPriorYear: 0.03,
      },
    ],
  },
  {
    id: 'dod',
    name: 'Department of Defense',
    allocated: 850000000000, // $850B
    spent: 720000000000,
    categoryType: 'department',
    description: 'Military operations, personnel, and procurement',
    changeFromPriorYear: 0.038, // 3.8% increase
    subcategories: [
      {
        id: 'army',
        name: 'Department of the Army',
        allocated: 185000000000,
        spent: 160000000000,
        categoryType: 'branch',
        description: 'Ground forces operations and equipment',
        changeFromPriorYear: 0.025,
        subcategories: [
          {
            id: 'army-personnel',
            name: 'Military Personnel',
            allocated: 70000000000,
            spent: 68000000000,
            categoryType: 'program',
            changeFromPriorYear: 0.04,
          },
          {
            id: 'army-operations',
            name: 'Operations & Maintenance',
            allocated: 65000000000,
            spent: 58000000000,
            categoryType: 'operations',
            changeFromPriorYear: 0.02,
          },
          {
            id: 'army-procurement',
            name: 'Procurement',
            allocated: 35000000000,
            spent: 25000000000,
            categoryType: 'program',
            changeFromPriorYear: 0.015,
          },
          {
            id: 'army-rdt',
            name: 'Research & Development',
            allocated: 15000000000,
            spent: 9000000000,
            categoryType: 'program',
            changeFromPriorYear: 0.035,
          },
        ],
      },
      {
        id: 'navy',
        name: 'Department of the Navy',
        allocated: 255000000000,
        spent: 215000000000,
        categoryType: 'branch',
        description: 'Naval and Marine Corps operations',
        changeFromPriorYear: 0.045,
        subcategories: [
          {
            id: 'navy-personnel',
            name: 'Military Personnel',
            allocated: 58000000000,
            spent: 56000000000,
            categoryType: 'program',
            changeFromPriorYear: 0.035,
          },
          {
            id: 'navy-operations',
            name: 'Operations & Maintenance',
            allocated: 75000000000,
            spent: 68000000000,
            categoryType: 'operations',
            changeFromPriorYear: 0.03,
          },
          {
            id: 'navy-shipbuilding',
            name: 'Shipbuilding & Conversion',
            allocated: 32000000000,
            spent: 20000000000,
            categoryType: 'program',
            changeFromPriorYear: 0.08,
          },
          {
            id: 'navy-aircraft',
            name: 'Aircraft Procurement',
            allocated: 45000000000,
            spent: 35000000000,
            categoryType: 'program',
            changeFromPriorYear: 0.06,
          },
          {
            id: 'navy-rdt',
            name: 'Research & Development',
            allocated: 25000000000,
            spent: 18000000000,
            categoryType: 'program',
            changeFromPriorYear: 0.05,
          },
        ],
      },
      {
        id: 'airforce',
        name: 'Department of the Air Force',
        allocated: 215000000000,
        spent: 180000000000,
        categoryType: 'branch',
        description: 'Air and space operations',
        changeFromPriorYear: 0.042,
        subcategories: [
          {
            id: 'af-personnel',
            name: 'Military Personnel',
            allocated: 55000000000,
            spent: 53000000000,
            categoryType: 'program',
            changeFromPriorYear: 0.038,
          },
          {
            id: 'af-operations',
            name: 'Operations & Maintenance',
            allocated: 70000000000,
            spent: 62000000000,
            categoryType: 'operations',
            changeFromPriorYear: 0.025,
          },
          {
            id: 'af-aircraft',
            name: 'Aircraft Procurement',
            allocated: 45000000000,
            spent: 32000000000,
            categoryType: 'program',
            changeFromPriorYear: 0.055,
          },
          {
            id: 'af-space',
            name: 'Space Systems',
            allocated: 28000000000,
            spent: 20000000000,
            categoryType: 'program',
            changeFromPriorYear: 0.12, // Space Force growth
          },
          {
            id: 'af-rdt',
            name: 'Research & Development',
            allocated: 17000000000,
            spent: 13000000000,
            categoryType: 'program',
            changeFromPriorYear: 0.04,
          },
        ],
      },
      {
        id: 'dod-wide',
        name: 'Defense-Wide Programs',
        allocated: 125000000000,
        spent: 105000000000,
        categoryType: 'program',
        description: 'Joint programs, special operations, missile defense',
        changeFromPriorYear: 0.048,
        subcategories: [
          {
            id: 'socom',
            name: 'Special Operations Command',
            allocated: 15000000000,
            spent: 13000000000,
            categoryType: 'program',
            changeFromPriorYear: 0.055,
          },
          {
            id: 'mda',
            name: 'Missile Defense Agency',
            allocated: 30000000000,
            spent: 24000000000,
            categoryType: 'agency',
            changeFromPriorYear: 0.07,
          },
          {
            id: 'dia',
            name: 'Defense Intelligence Agency',
            allocated: 8000000000,
            spent: 7200000000,
            categoryType: 'agency',
            changeFromPriorYear: 0.04,
          },
          {
            id: 'cybercom',
            name: 'Cyber Command',
            allocated: 12000000000,
            spent: 10000000000,
            categoryType: 'program',
            changeFromPriorYear: 0.15, // Cyber priority
          },
        ],
      },
      {
        id: 'dod-oversight',
        name: 'Office of the Secretary of Defense',
        allocated: 70000000000,
        spent: 60000000000,
        categoryType: 'operations',
        description: 'OSD operations and support',
        changeFromPriorYear: 0.02,
      },
    ],
  },
  {
    id: 'va',
    name: 'Department of Veterans Affairs',
    allocated: 300000000000, // $300B
    spent: 270000000000,
    categoryType: 'department',
    description: 'Veterans benefits, healthcare, and services',
    changeFromPriorYear: 0.052, // 5.2% increase
    subcategories: [
      {
        id: 'va-healthcare',
        name: 'Veterans Health Administration',
        allocated: 130000000000,
        spent: 120000000000,
        categoryType: 'program',
        description: 'VA medical care and facilities',
        changeFromPriorYear: 0.065,
      },
      {
        id: 'va-benefits',
        name: 'Veterans Benefits Administration',
        allocated: 150000000000,
        spent: 138000000000,
        categoryType: 'program',
        description: 'Disability compensation and pensions',
        changeFromPriorYear: 0.045,
      },
      {
        id: 'va-memorial',
        name: 'National Cemetery Administration',
        allocated: 400000000,
        spent: 380000000,
        categoryType: 'program',
        description: 'Veterans cemeteries',
        changeFromPriorYear: 0.02,
      },
      {
        id: 'va-it',
        name: 'IT Modernization',
        allocated: 6000000000,
        spent: 4500000000,
        categoryType: 'operations',
        description: 'Electronic health records and systems',
        changeFromPriorYear: 0.25,
      },
    ],
  },
  {
    id: 'dhs',
    name: 'Department of Homeland Security',
    allocated: 60000000000, // $60B
    spent: 52000000000,
    categoryType: 'department',
    description: 'Border security, immigration, disaster response, cybersecurity',
    changeFromPriorYear: 0.058, // 5.8% increase
    subcategories: [
      {
        id: 'cbp',
        name: 'Customs and Border Protection',
        allocated: 18500000000,
        spent: 16800000000,
        categoryType: 'agency',
        description: 'Border security and trade enforcement',
        changeFromPriorYear: 0.08,
        subcategories: [
          {
            id: 'border-patrol',
            name: 'U.S. Border Patrol',
            allocated: 5200000000,
            spent: 4900000000,
            categoryType: 'program',
            changeFromPriorYear: 0.095,
          },
          {
            id: 'ofo',
            name: 'Office of Field Operations',
            allocated: 5000000000,
            spent: 4700000000,
            categoryType: 'program',
            changeFromPriorYear: 0.06,
          },
          {
            id: 'amt',
            name: 'Air and Marine Operations',
            allocated: 900000000,
            spent: 820000000,
            categoryType: 'program',
            changeFromPriorYear: 0.04,
          },
        ],
      },
      {
        id: 'ice',
        name: 'Immigration and Customs Enforcement',
        allocated: 9500000000,
        spent: 8700000000,
        categoryType: 'agency',
        description: 'Immigration enforcement and investigations',
        changeFromPriorYear: 0.12, // 12% increase
        subcategories: [
          {
            id: 'ero',
            name: 'Enforcement and Removal Operations',
            allocated: 5500000000,
            spent: 5100000000,
            categoryType: 'program',
            description: 'Detention and deportation operations',
            changeFromPriorYear: 0.15,
          },
          {
            id: 'hsi',
            name: 'Homeland Security Investigations',
            allocated: 2800000000,
            spent: 2600000000,
            categoryType: 'program',
            description: 'Criminal investigations',
            changeFromPriorYear: 0.08,
          },
          {
            id: 'ice-ops',
            name: 'Mission Support',
            allocated: 1200000000,
            spent: 1000000000,
            categoryType: 'operations',
            changeFromPriorYear: 0.05,
          },
        ],
      },
      {
        id: 'tsa',
        name: 'Transportation Security Administration',
        allocated: 10500000000,
        spent: 9800000000,
        categoryType: 'agency',
        description: 'Aviation and transportation security',
        changeFromPriorYear: 0.035,
        subcategories: [
          {
            id: 'tsa-screening',
            name: 'Aviation Screening',
            allocated: 7500000000,
            spent: 7100000000,
            categoryType: 'program',
            changeFromPriorYear: 0.04,
          },
          {
            id: 'tsa-tech',
            name: 'Security Technology',
            allocated: 1500000000,
            spent: 1200000000,
            categoryType: 'program',
            changeFromPriorYear: 0.08,
          },
        ],
      },
      {
        id: 'uscg',
        name: 'U.S. Coast Guard',
        allocated: 13000000000,
        spent: 11800000000,
        categoryType: 'agency',
        description: 'Maritime security and search & rescue',
        changeFromPriorYear: 0.042,
        subcategories: [
          {
            id: 'uscg-ops',
            name: 'Operating Expenses',
            allocated: 9000000000,
            spent: 8500000000,
            categoryType: 'operations',
            changeFromPriorYear: 0.038,
          },
          {
            id: 'uscg-procurement',
            name: 'Acquisition & Construction',
            allocated: 3500000000,
            spent: 2800000000,
            categoryType: 'program',
            changeFromPriorYear: 0.055,
          },
        ],
      },
      {
        id: 'fema',
        name: 'Federal Emergency Management Agency',
        allocated: 6000000000,
        spent: 5200000000,
        categoryType: 'agency',
        description: 'Disaster response and emergency management',
        changeFromPriorYear: -0.02, // Slight decrease in base budget
        subcategories: [
          {
            id: 'fema-grants',
            name: 'State and Local Grants',
            allocated: 2500000000,
            spent: 2200000000,
            categoryType: 'program',
            changeFromPriorYear: -0.05,
          },
          {
            id: 'fema-drf',
            name: 'Disaster Relief Fund',
            allocated: 2000000000,
            spent: 1800000000,
            categoryType: 'program',
            description: 'Emergency disaster response',
            changeFromPriorYear: 0.0,
          },
          {
            id: 'fema-ops',
            name: 'Operations',
            allocated: 1500000000,
            spent: 1200000000,
            categoryType: 'operations',
            changeFromPriorYear: 0.02,
          },
        ],
      },
      {
        id: 'cisa',
        name: 'Cybersecurity & Infrastructure Security Agency',
        allocated: 3000000000,
        spent: 2500000000,
        categoryType: 'agency',
        description: 'Cybersecurity and critical infrastructure protection',
        changeFromPriorYear: 0.18, // High growth area
      },
    ],
  },
  {
    id: 'education',
    name: 'Department of Education',
    allocated: 80000000000, // $80B
    spent: 72000000000,
    categoryType: 'department',
    description: 'Federal education programs and student aid',
    changeFromPriorYear: 0.015,
    subcategories: [
      {
        id: 'title-i',
        name: 'Title I Grants',
        allocated: 18000000000,
        spent: 17500000000,
        categoryType: 'program',
        description: 'Aid to disadvantaged schools',
        changeFromPriorYear: 0.02,
      },
      {
        id: 'pell',
        name: 'Pell Grants',
        allocated: 28000000000,
        spent: 27000000000,
        categoryType: 'program',
        description: 'College financial aid for low-income students',
        changeFromPriorYear: 0.04,
      },
      {
        id: 'idea',
        name: 'Special Education (IDEA)',
        allocated: 15000000000,
        spent: 14500000000,
        categoryType: 'program',
        description: 'Special education services',
        changeFromPriorYear: 0.025,
      },
      {
        id: 'student-loans',
        name: 'Student Loan Programs',
        allocated: 12000000000,
        spent: 10000000000,
        categoryType: 'program',
        description: 'Federal student loan servicing',
        changeFromPriorYear: -0.05,
      },
    ],
  },
  {
    id: 'transportation',
    name: 'Department of Transportation',
    allocated: 105000000000, // $105B
    spent: 88000000000,
    categoryType: 'department',
    description: 'Highway, transit, aviation, and rail infrastructure',
    changeFromPriorYear: 0.068, // Infrastructure investment boost
    subcategories: [
      {
        id: 'fhwa',
        name: 'Federal Highway Administration',
        allocated: 55000000000,
        spent: 48000000000,
        categoryType: 'agency',
        description: 'Highway construction and maintenance',
        changeFromPriorYear: 0.075,
      },
      {
        id: 'fta',
        name: 'Federal Transit Administration',
        allocated: 18000000000,
        spent: 15000000000,
        categoryType: 'agency',
        description: 'Public transit grants',
        changeFromPriorYear: 0.09,
      },
      {
        id: 'faa',
        name: 'Federal Aviation Administration',
        allocated: 19000000000,
        spent: 17500000000,
        categoryType: 'agency',
        description: 'Aviation safety and air traffic control',
        changeFromPriorYear: 0.045,
      },
      {
        id: 'fra',
        name: 'Federal Railroad Administration',
        allocated: 5000000000,
        spent: 3500000000,
        categoryType: 'agency',
        description: 'Rail safety and Amtrak support',
        changeFromPriorYear: 0.12,
      },
    ],
  },
  {
    id: 'agriculture',
    name: 'Department of Agriculture',
    allocated: 180000000000, // $180B
    spent: 165000000000,
    categoryType: 'department',
    description: 'Farm subsidies, nutrition programs, rural development',
    changeFromPriorYear: 0.038,
    subcategories: [
      {
        id: 'snap',
        name: 'Supplemental Nutrition Assistance Program',
        allocated: 115000000000,
        spent: 110000000000,
        categoryType: 'program',
        description: 'Food assistance for low-income families',
        changeFromPriorYear: 0.025,
      },
      {
        id: 'school-lunch',
        name: 'Child Nutrition Programs',
        allocated: 28000000000,
        spent: 27000000000,
        categoryType: 'program',
        description: 'School meals',
        changeFromPriorYear: 0.035,
      },
      {
        id: 'farm-subsidies',
        name: 'Farm Support Programs',
        allocated: 22000000000,
        spent: 18000000000,
        categoryType: 'program',
        description: 'Crop insurance and farm subsidies',
        changeFromPriorYear: 0.05,
      },
      {
        id: 'forest-service',
        name: 'U.S. Forest Service',
        allocated: 8000000000,
        spent: 7000000000,
        categoryType: 'agency',
        description: 'National forest management',
        changeFromPriorYear: 0.045,
      },
    ],
  },
  {
    id: 'hud',
    name: 'Department of Housing and Urban Development',
    allocated: 70000000000, // $70B
    spent: 63000000000,
    categoryType: 'department',
    description: 'Public housing, rental assistance, community development',
    changeFromPriorYear: 0.028,
    subcategories: [
      {
        id: 'section-8',
        name: 'Housing Choice Vouchers (Section 8)',
        allocated: 32000000000,
        spent: 30000000000,
        categoryType: 'program',
        description: 'Rental assistance for low-income families',
        changeFromPriorYear: 0.04,
      },
      {
        id: 'public-housing',
        name: 'Public Housing',
        allocated: 8500000000,
        spent: 8000000000,
        categoryType: 'program',
        description: 'Public housing operations',
        changeFromPriorYear: 0.015,
      },
      {
        id: 'cdbg',
        name: 'Community Development Block Grants',
        allocated: 3500000000,
        spent: 3200000000,
        categoryType: 'program',
        description: 'Local community development',
        changeFromPriorYear: -0.02,
      },
      {
        id: 'homeless',
        name: 'Homeless Assistance Grants',
        allocated: 3800000000,
        spent: 3500000000,
        categoryType: 'program',
        description: 'Homelessness prevention and services',
        changeFromPriorYear: 0.08,
      },
    ],
  },
  {
    id: 'justice',
    name: 'Department of Justice',
    allocated: 40000000000, // $40B
    spent: 36000000000,
    categoryType: 'department',
    description: 'Federal law enforcement, prisons, legal services',
    changeFromPriorYear: 0.042,
    subcategories: [
      {
        id: 'fbi',
        name: 'Federal Bureau of Investigation',
        allocated: 11000000000,
        spent: 10200000000,
        categoryType: 'agency',
        description: 'Federal criminal investigations',
        changeFromPriorYear: 0.05,
      },
      {
        id: 'bop',
        name: 'Bureau of Prisons',
        allocated: 8500000000,
        spent: 8000000000,
        categoryType: 'agency',
        description: 'Federal prison operations',
        changeFromPriorYear: 0.03,
      },
      {
        id: 'dea',
        name: 'Drug Enforcement Administration',
        allocated: 3500000000,
        spent: 3200000000,
        categoryType: 'agency',
        description: 'Drug trafficking enforcement',
        changeFromPriorYear: 0.025,
      },
      {
        id: 'atf',
        name: 'Bureau of Alcohol, Tobacco, Firearms & Explosives',
        allocated: 1700000000,
        spent: 1600000000,
        categoryType: 'agency',
        description: 'Firearms and explosives enforcement',
        changeFromPriorYear: 0.04,
      },
    ],
  },
  {
    id: 'state',
    name: 'Department of State',
    allocated: 58000000000, // $58B
    spent: 50000000000,
    categoryType: 'department',
    description: 'Foreign affairs, diplomacy, foreign aid',
    changeFromPriorYear: 0.032,
    subcategories: [
      {
        id: 'foreign-ops',
        name: 'Diplomatic Operations',
        allocated: 12000000000,
        spent: 11000000000,
        categoryType: 'operations',
        description: 'Embassy operations and personnel',
        changeFromPriorYear: 0.04,
      },
      {
        id: 'foreign-aid',
        name: 'Foreign Assistance',
        allocated: 40000000000,
        spent: 35000000000,
        categoryType: 'program',
        description: 'Economic and military aid',
        changeFromPriorYear: 0.025,
      },
      {
        id: 'security-assistance',
        name: 'International Security Assistance',
        allocated: 6000000000,
        spent: 4000000000,
        categoryType: 'program',
        description: 'Military aid and training',
        changeFromPriorYear: 0.05,
      },
    ],
  },
  {
    id: 'energy',
    name: 'Department of Energy',
    allocated: 48000000000, // $48B
    spent: 40000000000,
    categoryType: 'department',
    description: 'Energy research, nuclear security, environmental cleanup',
    changeFromPriorYear: 0.055,
    subcategories: [
      {
        id: 'nnsa',
        name: 'National Nuclear Security Administration',
        allocated: 23000000000,
        spent: 20000000000,
        categoryType: 'agency',
        description: 'Nuclear weapons and naval reactors',
        changeFromPriorYear: 0.06,
      },
      {
        id: 'energy-programs',
        name: 'Energy Programs',
        allocated: 8000000000,
        spent: 6500000000,
        categoryType: 'program',
        description: 'Renewable energy research',
        changeFromPriorYear: 0.12,
      },
      {
        id: 'em',
        name: 'Environmental Management',
        allocated: 7500000000,
        spent: 6000000000,
        categoryType: 'program',
        description: 'Nuclear site cleanup',
        changeFromPriorYear: 0.02,
      },
    ],
  },
  {
    id: 'labor',
    name: 'Department of Labor',
    allocated: 85000000000, // $85B
    spent: 77000000000,
    categoryType: 'department',
    description: 'Unemployment insurance, job training, worker protection',
    changeFromPriorYear: 0.022,
    subcategories: [
      {
        id: 'ui',
        name: 'Unemployment Insurance',
        allocated: 35000000000,
        spent: 33000000000,
        categoryType: 'program',
        description: 'Unemployment benefits',
        changeFromPriorYear: -0.15, // Post-pandemic decrease
      },
      {
        id: 'job-training',
        name: 'Job Training Programs',
        allocated: 3500000000,
        spent: 3200000000,
        categoryType: 'program',
        description: 'Workforce development',
        changeFromPriorYear: 0.08,
      },
      {
        id: 'osha',
        name: 'Occupational Safety & Health Administration',
        allocated: 700000000,
        spent: 650000000,
        categoryType: 'agency',
        description: 'Workplace safety enforcement',
        changeFromPriorYear: 0.04,
      },
    ],
  },
  {
    id: 'interior',
    name: 'Department of the Interior',
    allocated: 18000000000, // $18B
    spent: 16000000000,
    categoryType: 'department',
    description: 'National parks, public lands, Native American affairs',
    changeFromPriorYear: 0.048,
    subcategories: [
      {
        id: 'nps',
        name: 'National Park Service',
        allocated: 3500000000,
        spent: 3200000000,
        categoryType: 'agency',
        description: 'National park operations',
        changeFromPriorYear: 0.055,
      },
      {
        id: 'bia',
        name: 'Bureau of Indian Affairs',
        allocated: 3800000000,
        spent: 3500000000,
        categoryType: 'agency',
        description: 'Native American programs',
        changeFromPriorYear: 0.06,
      },
      {
        id: 'blm',
        name: 'Bureau of Land Management',
        allocated: 1500000000,
        spent: 1400000000,
        categoryType: 'agency',
        description: 'Public lands management',
        changeFromPriorYear: 0.03,
      },
    ],
  },
  {
    id: 'epa',
    name: 'Environmental Protection Agency',
    allocated: 11000000000, // $11B
    spent: 9500000000,
    categoryType: 'agency',
    description: 'Environmental regulation and cleanup',
    changeFromPriorYear: 0.028,
    subcategories: [
      {
        id: 'superfund',
        name: 'Superfund',
        allocated: 1700000000,
        spent: 1500000000,
        categoryType: 'program',
        description: 'Hazardous waste cleanup',
        changeFromPriorYear: 0.04,
      },
      {
        id: 'water-programs',
        name: 'Water Infrastructure',
        allocated: 4000000000,
        spent: 3500000000,
        categoryType: 'program',
        description: 'Clean water grants',
        changeFromPriorYear: 0.06,
      },
    ],
  },
  {
    id: 'nasa',
    name: 'National Aeronautics and Space Administration',
    allocated: 27000000000, // $27B
    spent: 23000000000,
    categoryType: 'agency',
    description: 'Space exploration and aeronautics research',
    changeFromPriorYear: 0.048,
    subcategories: [
      {
        id: 'artemis',
        name: 'Artemis Moon Program',
        allocated: 7500000000,
        spent: 6000000000,
        categoryType: 'program',
        description: 'Moon landing program',
        changeFromPriorYear: 0.12,
      },
      {
        id: 'iss',
        name: 'International Space Station',
        allocated: 3800000000,
        spent: 3600000000,
        categoryType: 'program',
        description: 'ISS operations',
        changeFromPriorYear: 0.02,
      },
      {
        id: 'science',
        name: 'Science Missions',
        allocated: 8000000000,
        spent: 7000000000,
        categoryType: 'program',
        description: 'Earth and space science',
        changeFromPriorYear: 0.05,
      },
    ],
  },
  {
    id: 'nsf',
    name: 'National Science Foundation',
    allocated: 10000000000, // $10B
    spent: 8500000000,
    categoryType: 'agency',
    description: 'Basic scientific research funding',
    changeFromPriorYear: 0.065,
  },
];
